### ISSUE TITLE
xinput-configure-pointer typo

### ISSUE THREAD

**Issue by thisisgregm** [SimonLammer/dotfiles#22]
The is a typo in the xinput-configure-pointer script (which I stumbled across on askubuntu / stackexchange)

Lines 25-29 say:

```
# Select orientation
o1="0°C"
o2="90°C"
o3="180°C"
o4="270°C"
```

It should be 0°, 90°, etc (without C), as they are degrees (rotation), not degrees Celsius (temperature) ;)

**Comment by SimonLammer** [comment]
Thank you, that's correct.
Fixed in commit 0ac1922055ca0640d850809006d61798aa20c927
